package entities

import "time"

// APIKey represents an API key entity whose identifiers are generated by the service.
type APIKey struct {
	KeyID       string     `json:"KeyID" gorm:"type:char(36);primaryKey" odata:"key,generate=uuid"`
	Owner       string     `json:"Owner" gorm:"not null" odata:"required,maxlength=100"`
	Description string     `json:"Description" odata:"maxlength=200"`
	CreatedAt   time.Time  `json:"CreatedAt" gorm:"not null"`
	ExpiresAt   *time.Time `json:"ExpiresAt" odata:"nullable"`
}

// GetSampleAPIKeys returns API keys that seed the development database.
func GetSampleAPIKeys() []APIKey {
	now := time.Now().UTC()
	expiresSoon := now.Add(30 * 24 * time.Hour)
	expired := now.Add(-7 * 24 * time.Hour)

	return []APIKey{
		{
			KeyID:       "e7c9d5fe-19e2-4c88-8e3b-79de0cf4af01",
			Owner:       "Integration Tests",
			Description: "Used by automated integration flows",
			CreatedAt:   now.Add(-90 * 24 * time.Hour),
			ExpiresAt:   &expiresSoon,
		},
		{
			KeyID:       "4f6d8d3a-7f24-4be1-9d22-4fd991745af3",
			Owner:       "Developer Sandbox",
			Description: "Local development experiments",
			CreatedAt:   now.Add(-60 * 24 * time.Hour),
			ExpiresAt:   nil,
		},
		{
			KeyID:       "0a3b6a7e-fd15-4f36-8e7e-01bd3586ef92",
			Owner:       "Deprecated Client",
			Description: "Legacy client slated for removal",
			CreatedAt:   now.Add(-180 * 24 * time.Hour),
			ExpiresAt:   &expired,
		},
	}
}
