version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - prealloc
  
  settings:
    gocyclo:
      min-complexity: 45
    errcheck:
      check-type-assertions: true
      check-blank: true
  
  exclusions:
    paths:
      - "test/expand_filter_integration_test.go"
      - "test/metadata_integration_test.go"
      - "cmd/"
    rules:
      # Exclude some linters from running on test files.
      - linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - unparam
        path: "_test\\.go"
      # Exclude gocyclo from complex test functions
      - linters:
          - gocyclo
        text: "TestExpandWithFilterIntegration|TestMetadataIntegrationJSON"
      # Exclude SA5011 related information messages (not actual errors)
      - linters:
          - staticcheck
        text: "SA5011\\(related information\\)"
      # Meter instrument creation errors are unlikely and handled gracefully
      - linters:
          - errcheck
        path: "internal/observability/(metrics|noop)\\.go"
        text: "meter\\.(Float64Histogram|Int64Counter|Int64Histogram)"
