run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - copyloopvar
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    # Exclude some linters from running on test files.
    - linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unparam
      path: "_test\\.go"
